# Generated by Django 2.0.4 on 2018-07-03 16:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-id',), 'verbose_name': 'Xəbər', 'verbose_name_plural': 'Xəbərlər'},
        ),
        migrations.AddField(
            model_name='article',
            name='publish_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
